### ISSUE TITLE
Language titles are displaying ** **

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-reference#7]
The title of the language-specific code snippets are displaying the "**" meant to bold the title. Remove the spaces between the "**" to bold the title. They seem to be in every reference file.

https://github.com/hashgraph/hedera-sdk/blob/master/reference/core/Client.md#-java-

**Comment by janaakhterov** [comment]
The reason there are two asterisks around the language code is because when running the server using `yarn serve` the language specific examples will be tabbed 
![image](https://user-images.githubusercontent.com/36461294/135189401-fe62064f-3210-436f-a5d3-892428250d09.png)

The references are written in markdown, but they will be transpiled into HTML/CSS/JS
